### ISSUE TITLE
OSC and Arduino Uno WiFi Rev2

### ISSUE THREAD

**Issue by educhemin** [CNMAT/OSC#106]
Hello,

It seems that OSC library 1.3.5 doesn't work with Arduino Uno WiFi Rev2.

Inserting `#include <OSCMessage.h>` in my sketch gives me the message :

> Arduino: 1.8.10 (Mac OS X), Board: "Arduino Uno WiFi Rev2, ATMEGA328"
> 
> Multiple libraries were found for "SPI.h"
>  Used: /Users/emmanuel/Library/Arduino15/packages/arduino/hardware/megaavr/1.8.5/libraries/SPI
> Multiple libraries were found for "WiFiNINA.h"
>  Used: /Users/emmanuel/Documents/Arduino/libraries/WiFiNINA
> Multiple libraries were found for "OSCMessage.h"
>  Used: /Users/emmanuel/Documents/Arduino/libraries/OSC
> In file included from /Users/emmanuel/Documents/Arduino/libraries/OSC/SLIPEncodedSerial.cpp:1:0:
> /Users/emmanuel/Documents/Arduino/libraries/OSC/SLIPEncodedSerial.h:11:10: fatal error: HardwareSerial.h: No such file or directory
>  #include <HardwareSerial.h>
>           ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> exit status 1
> Error compiling for board Arduino Uno WiFi Rev2.

It doesn't seems to be an SPI or WifiNINA library issue, they work fine without OSC...

Any solution ? Any chance for an update ?
Thanks !

**Comment by sstaub** [comment]
see PR #104

**Comment by educhemin** [comment]
Thanks a lot !

Emmanuel Duchemin
-----------------------------
+33 (0)6 10 25 27 92
e.duchemin@online.fr
