### ISSUE TITLE
Problem sending bundles in quick succession from Max

### ISSUE THREAD

**Issue by natcl** [CNMAT/OSC#118]
I have this strange issue when trying to read bundles on Teensy/Arduino Uno where I will get an `INVALID_OSC` error if I try to send 2 or more bundles in quick succession from Max/MSP.

The patch is very simple:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/77556/108118489-68aed800-706c-11eb-918e-49e978cecb66.png">

The test code (included below) is pretty straightforward too.

I tried also sending the OSC data from Max to Node-RED and compared the bytes received there with the bytes received by the Arduino and it's exactly the same.

Here are the byte that are sent:
```json
[35,98,117,110,100,108,101,0,0,0,0,0,0,0,0,1,0,0,0,16,47,116,101,115,116,0,0,0,44,105,0,0,0,0,0,255]
[35,98,117,110,100,108,101,0,0,0,0,0,0,0,0,1,0,0,0,16,47,116,101,115,116,0,0,0,44,105,0,0,0,0,0,255]
```

```c
#include <OSCBundle.h>
#include <OSCBoards.h>

#ifdef BOARD_HAS_USB_SERIAL
#include <SLIPEncodedUSBSerial.h>
SLIPEncodedUSBSerial SLIPSerial( thisBoardsSerialUSB );
#else
#include <SLIPEncodedSerial.h>
 SLIPEncodedSerial SLIPSerial(Serial);
#endif

void setup() {
  SLIPSerial.begin(115200);
}

void test(OSCMessage &msg) {
  if (msg.isInt(0)) {
    Serial.println(msg.getInt(0));
  }
}

void loop() {
  OSCBundle bundleIN;
  int size;
  
  while(!SLIPSerial.endofPacket()) {
    if( (size = SLIPSerial.available()) > 0) {
       while(size--) {
         bundleIN.fill(SLIPSerial.read());
       }  
     }
  }
  if(!bundleIN.hasError()) {
    bundleIN.dispatch("/test", test);
   
  } else {
    Serial.print("Error: ");
    Serial.println(bundleIN.getError());
  }
  bundleIN.empty();
}
```
[oscBug.zip](https://github.com/CNMAT/OSC/files/5991536/oscBug.zip)

**Comment by adrianfreed** [comment]
I pushed a potential fix for this kind of thing
