### ISSUE TITLE
SAMD21 / SAMD51 / W5500

### ISSUE THREAD

**Issue by juliusPeters** [CNMAT/OSC#133]
Hello Adrian,
thank you for your work.

The SAMD21 / W5500 combination seems to work fine when using Ethernet2/EthernetUdp2 libs. I also tried it with the SAMD51 / W5500 combination but failed to get results. 
You write M0 boards are supported but you do not mention the newer M4+ boards. Therefore, my question, are there some special requirements to use the library on a SAMD51 or is this processor simply not supported yet. Are there are plans to support it?

Thank you
Julius

**Comment by marccolemont** [comment]
Any update on this? Sending OSC command work perfect, Receiving OSC messages are corrupt from any device on the network. For example sending /test1/1 to the SAMD21 gives error 2, and reading what comes in is this:
��HI0""q"Iu  OSC Message Error

code:
...
OSCMessage MessageIN;
  int size;
  if ( (size = Udp.parsePacket()) > 0)
  {
    // digitalWrite(ledPin, HIGH);
    while (size--)
      SerialUSB << F(Udp.read());
    MessageIN.fill(Udp.read());
    //MessageIN.dispatch("/slomo/refresh",refresh);
    MessageIN.route("/slomo/refresh", refresh);

    if (!MessageIN.hasError()) {
      SerialUSB << F("  OSC Message received\n");

      // SloMo Project commands
      //MessageIN.route("/slomo/refresh", refresh);
    } else {
      SerialUSB << F("  OSC Message Error\n");
      error = MessageIN.getError();

      SerialUSB.println(error);
    }
  }
...

**Comment by adrianfreed** [comment]
Their shouldn't be any platform differences. I would need a simpler repro example to work on this
