### ISSUE TITLE
OSCMessage::empty() is missing return statement

### ISSUE THREAD

**Issue by j-be** [CNMAT/OSC#51]
I think empty() is supposed to return *this, but it doesn't.

I'm not a C++ pro, so I'm not sure if I'm misinterpreting here or if it is a bug...

**Comment by bakercp** [comment]
This appears to be fixed now?

https://github.com/CNMAT/OSC/blob/master/OSCMessage.cpp#L84-L100

**Comment by j-be** [comment]
Yes, seems to have been fixed with commit 6922531f9d58bdfecf0bb8f08438a515801e852a.

Hencs, I'm closing it.
