### ISSUE TITLE
ESP32 implementation

### ISSUE THREAD

**Issue by PedroScreamerovsky** [CNMAT/OSC#59]
Hi,
i've tried this library with espressing esp32, but it's not working.
Is there a plan on supporting esp32 boards in the future?

edit: thanks to this article i've been able to run osc on the ESP32:
https://0110.be/posts/ESP32_Thing_as_xOSC_alternative

**Comment by resonantbreath** [comment]
I am still getting issues when I use strings instead of data using the posted library version.

**Comment by resonantbreath** [comment]
I ended up uncommenting OSCData(const char * s) from the OSCData.h and OSCData.cpp from the linked library and got strings to work.
