### ISSUE TITLE
Support for Arduino Zero etc.

### ISSUE THREAD

**Issue by sstaub** [CNMAT/OSC#61]
Can you add support for Arduino Zero, M0, M0pro, MKR1000 etc. with Atmel SAMD21 uc.

**Comment by adrianfreed** [comment]
working on it.

**Comment by PTS93** [comment]
That would be great. Is there anything in particular that is preventing this to work out of the box?

#58

**Comment by PTS93** [comment]
It seems to fail at the SLIP part. I took a look at bakercp's implementation of SLIP which is working great on the SAMD platform.
https://github.com/bakercp/PacketSerial

**Comment by adrianfreed** [comment]
Now works

**Comment by PTS93** [comment]
Thanks a lot, very much appreciated!
