### ISSUE TITLE
Forum to discus things?

### ISSUE THREAD

**Issue by BLCKPSTV** [CNMAT/OSC#67]
Hi, 

I can't find a forum where questions can be asked about CNMAT (In my case OSC related) externals.

I want to send analog data via esp8266 to max/msp. I managed to get osc messages in max/msp. 
But when I declare a constant variable for the analogpin. I don't get the result I want. 
Anyway this is not an issue with the osc github part. So doesn't really matter (but you're free to help me whenever you want! ) ;) 
The question is if cnmat has a portal/forum where such things can be asked or discussed upon!

**Comment by adrianfreed** [comment]
please direct the question to Jeff Lubow at CNMAT
