### ISSUE TITLE
example using buttons to send OCS messages

### ISSUE THREAD

**Issue by seanr2109** [CNMAT/OSC#75]
How easy is it to code something that uses say 6/8 inputs from buttons, on a Leonardo Ethernet board.
I want to build a device that has some buttons that each send a different OSC command out from each button on ethernet. 

Im not sure where to start with the examples provided but im sure it can't be to difficult to make one button work and copy the code a few times?

**Comment by adrianfreed** [comment]
It should be easy to modify one of the examples once you have a sketch that debounces the button presses.
